#!/usr/bin/env sh
set -e
set -o pipefail

# PRESYNC, TIME, UID and GID come from environment variables
# PRESYNC if you want to copy from host to container one time
# TIME affects how often to sync
# UID and GID are the user/group ID to set synced files to,
#       _on the host_.

CONTAINER_DIR=/vol/container
HOST_DIR=/vol/host

function do_the_needful() {
    for FROM in ${1}/*; do
        [[ -d "${FROM}" ]] || continue
        TO="${2}/$(basename "${FROM}")"

        if [[ ! -d "${TO}" ]]; then
            cat << EOF
Volume "${FROM}" does not have a matching volume "${TO}"
EOF

            exit 1
        fi

        rsync \
            --archive \
            --chown=${UID}:${GID} \
            --delete \
            --verbose \
            ${FROM}/ ${TO}/
    done
}

RAN=0

while true; do
    sleep ${TIME};

    if [[ "${RAN}" -eq "0" ]] && [[ "${PRESYNC}" -eq "1" ]]; then
        printf "\n"
        printf "###########################################\n"
        printf "# Running one-time host -> container sync #\n"
        printf "###########################################\n"
        printf "\n"

        do_the_needful "${HOST_DIR}" "${CONTAINER_DIR}"
    fi

    printf "\n"
    printf "##################################\n"
    printf "# Running container -> host sync #\n"
    printf "##################################\n"
    printf "\n"

    do_the_needful "${CONTAINER_DIR}" "${HOST_DIR}"

    RAN=1
done
